from datetime import datetime
from typing import Optional

from app.tz import IST_TZ
from app.email.gmail_client import GmailClient, GmailMessage
from app.calendar.google_calendar_client import GoogleCalendarClient
from app.parsing.availability_parser import AvailabilityInterval, parse_availability
from app.scheduling.overlap_finder import find_overlapping_slots
from app.db.repository import (
    upsert_participant_and_store_availability,
    get_participant_emails,
    get_availabilities_for_participants,
)

# Keywords for detection
SCHEDULING_KEYWORDS = ["available", "free", "schedule", "meet", "meeting", "availability", "time slot"]
UPDATE_KEYWORDS = ["update", "status", "any news", "what happened"]

def detect_scheduling_request(text: str) -> bool:
    t = (text or "").lower()
    return any(k in t for k in SCHEDULING_KEYWORDS)

def detect_update_request(text: str) -> bool:
    t = (text or "").lower()
    return any(k in t for k in UPDATE_KEYWORDS)

def summarize_latest_thread_messages(messages: list[GmailMessage]) -> str:
    """
    Summarize the last 3 messages of a thread.
    """
    bodies: list[str] = []
    for m in messages[-3:]:
        body = (m.body_text or "").strip()
        if body:
            bodies.append(body)
    if not bodies:
        return "No recent message content found."

    parts: list[str] = []
    for idx, body in enumerate(bodies, start=1):
        one_line = " ".join(body.split())
        trimmed = one_line[:250] + ("..." if len(one_line) > 250 else "")
        parts.append(f"{idx}. {trimmed}")
    return "Recent context:\n" + "\n".join(parts)

def process_single_email(
    db_path: str,
    gmail: GmailClient,
    message_id: str,
    assistant_email: Optional[str] = None
) -> tuple[str, str, Optional[str]]:
    """
    Processes a single email and returns (action_taken, status, details).
    """
    original = gmail.get_message_full(message_id)
    subject = original.subject
    full_text = f"{original.subject}\n{original.from_email}\n{original.body_text}"
    
    action_taken = "ignored"
    status = "skipped"
    details = None
    
    scheduling_match = detect_scheduling_request(full_text)
    update_match = detect_update_request(full_text)
    
    if scheduling_match:
        action_taken = "scheduling"
        status = "success"
        
        reference_ist = datetime.now(IST_TZ)
        intervals = parse_availability(original.body_text, reference_ist=reference_ist)
        
        if not intervals:
            status = "no_availability"
            details = "No availability intervals found in email body."
        else:
            upsert_participant_and_store_availability(
                db_path,
                participant_email=original.from_email,
                intervals=[(i.start, i.end) for i in intervals],
                source_message_id=message_id,
            )

            participant_emails = get_participant_emails(db_path)
            raw_windows = get_availabilities_for_participants(db_path, participant_emails)

            participant_emails_filtered = []
            participant_intervals = []
            for email, windows in zip(participant_emails, raw_windows):
                if windows:
                    participant_emails_filtered.append(email)
                    participant_intervals.append([AvailabilityInterval(start=s, end=e) for (s, e) in windows])

            if len(participant_intervals) < 2:
                status = "not_enough_participants"
                details = "Need at least 2 participants with stored availability."
            else:
                overlap_segments = find_overlapping_slots(participant_intervals)
                if not overlap_segments:
                    status = "no_overlap"
                    details = "No overlapping slot found."
                else:
                    overlap = sorted(overlap_segments, key=lambda x: x.start)[0]
                    organizer_email = assistant_email or original.from_email
                    
                    calendar_event_id = "demo-event-123"
                    calendar_event_link = "https://calendar.google.com/event?demo"
                    try:
                        calendar_client = GoogleCalendarClient()
                        created_event_id, created_event_link = calendar_client.create_event(
                            summary="Scheduling Confirmation (AI)",
                            start_dt=overlap.start,
                            end_dt=overlap.end,
                            description=(
                                "This calendar event was generated by an experimental AI assistant.\n"
                                "It was created automatically based on overlapping availability extracted from emails."
                            ),
                            attendees_emails=participant_emails_filtered,
                        )
                        if created_event_id: calendar_event_id = created_event_id
                        if created_event_link: calendar_event_link = created_event_link
                    except Exception as e:
                        details = f"calendar_error: {str(e)}"

                    gmail.send_confirmation_reply(
                        to_email=original.from_email,
                        organizer_email=organizer_email,
                        original=original,
                        meeting_start_iso=overlap.start.isoformat(),
                        meeting_end_iso=overlap.end.isoformat(),
                        calendar_link=calendar_event_link,
                        participant_emails=participant_emails_filtered,
                    )
                    details = f"calendar_event_id={calendar_event_id}"

    elif update_match:
        action_taken = "update"
        status = "success"
        
        thread_messages = []
        if original.thread_id:
            try:
                thread_messages = gmail.get_thread_messages(original.thread_id)
            except:
                thread_messages = [original]

        summary = summarize_latest_thread_messages(thread_messages)
        disclaimer = "This email was generated by an experimental AI assistant."
        reply_body = f"{summary}\n\n{disclaimer}"

        organizer_email = assistant_email or original.from_email
        gmail.send_text_reply(
            to_email=original.from_email,
            organizer_email=organizer_email,
            original=original,
            subject=original.subject or "Update",
            body_text=reply_body,
        )
        
    return action_taken, status, details
